### ISSUE TITLE
For translating, use a translating platform

### ISSUE THREAD

**Issue by aha999** [KariariDiscord/multi-lang#1]
A lot of projects use a translating platform like [Weblate ](https://weblate.org//)as a translating platform.
If the project is open-source, the use of Weblate is free by being hosted on their servers. Weblate is also open-source and you can host it yourself.
By use a translation platform, translating is easy for anyone and you don't require technical skills, and you can have a widget on github page showing the progress of existing translations.

Similar to weblate, there's also Transifex and Crowdin, but they're not opensource.
Example of a project using it: [Link](https://hosted.weblate.org/projects/guardianproject/#languages)

**Comment by danclay** [comment]
This is planned in the revamp of the bot. As a result of the revamp, strings in most commands have been rewritten, rendering many currently translated strings outdated. This GitHub translation pack will be deprecated for this reason.

**Comment by comradekingu** [comment]
+1 for Hosted Weblate

**Comment by danclay** [comment]
The ravamp has been completed and Kariari now uses an online localization platform! Visit [this form](https://go.kariari.xyz/locale) to contribute.
